name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

     - name: Install deps
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt -r requirements-dev.txt

      - name: Lnt (flake8)
        run: flake8 mc_rsklab

      - name: Type check (mypy)
        run: mypy mc_rsklab --gnore-mssng-mports

      - name: Test (pytest)
        run: pytest -q
